name: Deploy Gamemodstudios Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment (Node v20)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'  # Cache node_modules for faster builds

      # Step 3: Install dependencies cleanly
      - name: Install dependencies
        run: npm ci

      # Step 4: Build and export the Next.js static site
      - name: Build and export Next.js app
        run: npm run build

      # Step 5: Deploy the static output to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out

